remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-slate
title: Brandon J. Kessler's Blog
description: My Personal Ramblings
timezone: America/Denver
excerpt_separator: <!--more-->
permalink: date