theme: jekyll-theme-slate
title: Brandon J. Kessler's Blog
description: My Personal Ramblings
timezone: America/Denver
excerpt_separator: <!--more-->
permalink: /:categories/:year/:month/:day/:title:output_ext